# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_test_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time_id', models.IntegerField()),
                ('test_tag', models.TextField()),
            ],
        ),
    ]
