# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_git_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git_subject', models.TextField()),
                ('git_author_name', models.TextField()),
                ('git_author_email', models.TextField()),
                ('git_hash_code', models.TextField()),
            ],
        ),
    ]
