# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_test_git_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_git_log',
            name='git_tested',
            field=models.TextField(default='False'),
        ),
    ]
