# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_test_git_log_git_tested'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_times',
            name='test_git_log_id',
            field=models.IntegerField(default=-1),
        ),
    ]
