# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_test_times_test_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_times',
            name='test_branch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='test_times',
            name='test_device_info_id',
            field=models.IntegerField(default=-1),
        ),
    ]
