# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_auto_20160202_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_device_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_sdk', models.TextField()),
                ('version_incremental', models.TextField()),
                ('product', models.TextField()),
                ('csc_version', models.TextField()),
                ('characristics', models.TextField()),
                ('sku', models.TextField()),
                ('device_id', models.TextField()),
            ],
        ),
    ]
