# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_test_results_test_extra_msgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_cases',
            name='test_threshold',
            field=models.TextField(default=''),
        ),
    ]
