# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_test_cases_test_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_cases',
            name='test_threshold',
            field=models.TextField(default='', null=True),
        ),
    ]
