# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20160204_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_results',
            name='test_extra_msgs',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='test_times',
            name='test_branch',
            field=models.TextField(default='', null=True),
        ),
    ]
