# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_test_git_log_git_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_extra_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.IntegerField()),
                ('test_time_id', models.IntegerField()),
                ('test_message_name', models.TextField(default='')),
                ('test_message_value', models.IntegerField(default=-1)),
                ('test_message_extra_messages', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='test_cases',
            name='test_threshold_value',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
