# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_auto_20160216_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.IntegerField()),
                ('test_branch', models.TextField(default='', null=True)),
                ('test_display_order', models.IntegerField(default=0, null=True)),
                ('test_threshold_name', models.TextField(default='', null=True)),
                ('test_threshold_value', models.IntegerField(default=-1, null=True)),
            ],
        ),
    ]
