# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_test_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_threshold',
            name='test_method_name',
            field=models.TextField(default='', null=True),
        ),
    ]
