# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_test_threshold_test_method_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_extra_messages',
            name='test_method_name',
            field=models.TextField(default='', null=True),
        ),
    ]
